import { Suspense } from 'react';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import LoadingProfile from '@/app/(users)/(content)/profile/[id]/loading';
import SidebarFull from '@/components/sidebar/tailwind/sidebar';

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarFull>
          <Suspense fallback={<LoadingProfile />}>
            {/* Background Effects */}
            <div className="absolute -z-10 inset-0 bg-gradient-to-br from-black via-black/95 to-transparent" />
            <div className="absolute -z-10 inset-0 bg-gradient-to-r from-violet-500/10 to-fuchsia-500/10 animate-gradient-xy" />
            {children}
          </Suspense>
        </SidebarFull>
      </body>
    </html>
  );
}
