import { Suspense } from 'react';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Footer from '@/components/shared/Footer';
import LoadingProfile from '../(users)/(content)/profile/[id]/loading';

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col lg:flex-row min-h-screen">
          <div className="w-full flex flex-col min-h-screen">
            <Suspense fallback={<LoadingProfile />}>
              {children}
            </Suspense>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
